#!/bin/bash

install_xorg-base(){
    local name="xorg-base"
    check_conf_exists $name
    lists $name

    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/.Xmodmap /home/$SUDO_USER/

    echo_ln ; echo_ok "$name installed." ; echo_ln
}

install_wm(){
    local name="wm"
    check_conf_exists $name

    deps $name

    for dir in $(cat $BASE_DIR/etc/$name/root.dirs); do
        $ROOT_INSTALL -d $dir
    done

    for dir in $(cat $BASE_DIR/etc/$name/usr.dirs); do
        $USR_INSTALL -d /home/$SUDO_USER/$dir
    done

    lists $name

    $USR_INSTALL --mode=744 $BASE_DIR/etc/$name/bspwmrc /home/$SUDO_USER/.config/bspwm/
    $USR_INSTALL --mode=744 $BASE_DIR/etc/$name/sxhkdrc /home/$SUDO_USER/.config/sxhkd/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/config.rasi /home/$SUDO_USER/.config/rofi/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/picom.conf /home/$SUDO_USER/.config/picom/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/polybar.ini /home/$SUDO_USER/.config/polybar/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/dunstrc /home/$SUDO_USER/.config/dunst/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/terminalrc /home/$SUDO_USER/.config/xfce4/terminal/

    # GVim only for +clipboard compilation
    update-alternatives --remove vi /usr/bin/vim.gtk3
    update-alternatives --remove vimdiff /usr/bin/vim.gtk3
    update-alternatives --remove editor /usr/bin/vim.gtk3
    update-alternatives --install /usr/bin/vi vi /usr/bin/vim.basic 1
    update-alternatives --install /usr/bin/vimdiff vimdiff /usr/bin/vim.basic 1
    update-alternatives --install /usr/bin/editor editor /usr/bin/vim.basic 1
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/.vimrc /home/$SUDO_USER/

    sed -i "s/CUSTOMUSER/$SUDO_USER/" $BASE_DIR/etc/$name/xfce4-screenshooter
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/xfce4-screenshooter /home/$SUDO_USER/.config/xfce4/

    # Custom scripts
    echo 'PATH="$PATH:/usr/local/libexec:/usr/local/sbin"' /etc/environment.d/99local-extra-paths.conf # Extra local dirs in global $PATH
    $ROOT_INSTALL --mode=744 $BASE_DIR/etc/$name/touchpad_init /usr/local/libexec/
    $ROOT_INSTALL --mode=744 $BASE_DIR/etc/$name/battery_poll /usr/local/libexec/
    $ROOT_INSTALL --mode=744 $BASE_DIR/etc/$name/switch_monitor_workspace /usr/local/libexec/
    $ROOT_INSTALL --mode=755 $BASE_DIR/etc/$name/brightness /usr/local/bin/
    $ROOT_INSTALL --mode=755 $BASE_DIR/etc/$name/powermenu /usr/local/bin/
    $ROOT_INSTALL --mode=755 $BASE_DIR/etc/$name/notify_usb_mount /usr/local/bin/
    $ROOT_INSTALL --mode=755 $BASE_DIR/etc/$name/lockscreen /usr/local/bin/
    $ROOT_INSTALL --mode=644 $BASE_DIR/etc/$name/powermenu.rasi /usr/local/lib/powermenu/

    # Theming: GRUB
    sed -i "s/^#GRUB_TERMINAL=console/GRUB_TERMINAL=console/" /etc/default/grub
    echo -e "[Daemon]\nTheme=text\nShowDelay=0" | tee /etc/plymouth/plymouthd.conf

    # Theming: at-deb-theme
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/at-deb-theme/fonts/fonts.conf /home/$SUDO_USER/.config/fontconfig/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/at-deb-theme/apps/Mousepad/at-deb-dark.xml /home/$SUDO_USER/.local/share/gtksourceview-4/styles/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/at-deb-theme/apps/Mousepad/at-deb-light.xml /home/$SUDO_USER/.local/share/gtksourceview-4/styles/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/at-deb-theme/apps/xfce4-terminal/at-deb.theme /home/$SUDO_USER/.local/share/xfce4/terminal/colorschemes/
    7z x $BASE_DIR/etc/$name/at-deb-theme/gtk-base/at-deb-dark.7z -o$BASE_DIR/etc/$name/at-deb-theme/gtk-base/
    7z x $BASE_DIR/etc/$name/at-deb-theme/gtk-base/at-deb-light.7z -o$BASE_DIR/etc/$name/at-deb-theme/gtk-base/
    7z x $BASE_DIR/etc/$name/at-deb-theme/gtk-lightdm/at-deb-dark-lightdm-greeter.7z -o$BASE_DIR/etc/$name/at-deb-theme/gtk-lightdm/
    7z x $BASE_DIR/etc/$name/at-deb-theme/icons/Boston-at-deb.7z -o$BASE_DIR/etc/$name/at-deb-theme/icons/
    rm -rf $BASE_DIR/etc/$name/at-deb-theme/gtk-base/at-deb-dark.7z
    rm -rf $BASE_DIR/etc/$name/at-deb-theme/gtk-base/at-deb-light.7z
    rm -rf $BASE_DIR/etc/$name/at-deb-theme/gtk-lightdm/at-deb-dark-lightdm-greeter.7z
    rm -rf $BASE_DIR/etc/$name/at-deb-theme/icons/Boston-at-deb.7z
    cp -r $BASE_DIR/etc/$name/at-deb-theme/ /usr/local/share/themes
    ln -s /usr/local/share/themes/at-deb-theme/gtk-base/at-deb-dark/ /usr/share/themes/
    ln -s /usr/local/share/themes/at-deb-theme/gtk-base/at-deb-light/ /usr/share/themes/
    ln -s /usr/local/share/themes/at-deb-theme/gtk-lightdm/at-deb-dark-lightdm-greeter/ /usr/share/themes/
    ln -s /usr/local/share/themes/at-deb-theme/icons/Boston-at-deb /usr/share/icons
    sed -i "/#greeter-hide-users=/c\greeter-hide-users=false" /etc/lightdm/lightdm.conf
    sed -i "/#greeter-allow-guest=/c\greeter-allow-guest=false" /etc/lightdm/lightdm.conf
    sed -i "/#allow-guest=/c\allow-guest=false" /etc/lightdm/lightdm.conf
    sed -i "/#background=/c\background=/usr/local/share/themes/at-deb-theme/wallpapers/default/login/1920x1080.png" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#user-background=/c\user-background=true" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#theme-name=/c\theme-name=at-deb-dark-lightdm-greeter" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#icon-theme-name=/c\icon-theme-name=Boston-at-deb" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#font-name=/c\font-name=Clear Sans Medium" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#indicators=/c\indicators=~power;~spacer;~clock" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#clock-format=/c\clock-format=%H:%M:%S" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#position=/c\position=42% 56%" /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "/#screensaver-timeout=/c\screensaver-timeout=70" /etc/lightdm/lightdm-gtk-greeter.conf
    echo "hide-user-image=true" | tee -a /etc/lightdm/lightdm-gtk-greeter.conf
    sed -i "s/CUSTOMUSER/$SUDO_USER/" $BASE_DIR/etc/$name/at-deb-theme/qt5-base/qt5ct.conf
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/at-deb-theme/qt5-base/qt5ct.conf /home/$SUDO_USER/.config/qt5ct/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/at-deb-theme/qt5-base/at-deb-dark.conf /home/$SUDO_USER/.config/qt5ct/colors/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/at-deb-theme/qt5-base/at-deb-dark-fixes.qss /home/$SUDO_USER/.config/qt5ct/qss/

    # Theming: themes -- switch between light/dark themes
    $ROOT_INSTALL --mode=755 $BASE_DIR/etc/$name/themes /usr/local/bin/
    echo 'Net/ThemeName "at-deb-dark"' | sudo -u $SUDO_USER tee /home/$SUDO_USER/.xsettingsd

    # Theming: wallpapers -- set default wallpaper
    $ROOT_INSTALL --mode=755 $BASE_DIR/etc/$name/wallpapers /usr/local/bin/
    $ROOT_INSTALL --mode=644 $BASE_DIR/etc/$name/wallpapers.rasi /usr/local/lib/wallpapers/
    addgroup wallpapers
    adduser $SUDO_USER wallpapers
    echo "default" | tee -a /var/local/wallpapers/current-wallpaper
    chown root:wallpapers /var/local/wallpapers/current-wallpaper
    chmod 774 /var/local/wallpapers/current-wallpaper

    # Theming: GTK settings
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/gtkfilechooser.ini /home/$SUDO_USER/.config/gtk-2.0/
    $USR_INSTALL --mode=644 $BASE_DIR/etc/$name/settings.ini /home/$SUDO_USER/.config/gtk-3.0/

    echo_ok "$name installed." ; echo_ln
}

install_misc-apps(){
    local name="misc-apps"
    check_conf_exists $name
    lists $name
    echo_ok "$name installed." ; echo_ln
}

install_xorg(){
    echo "Install xorg..."
    set_snapper_apt_rule 0
    echo_ln
    apt_routine
    echo_ln

    install_xorg-base
    install_wm
    install_misc-apps ; echo
    set_snapper_apt_rule 1
}