#!/bin/bash

configure(){
    echo "Configuring system..."
    local name="configure"
    set_snapper_apt_rule 0
    echo_ln
    apt_routine
    echo_ln
    check_conf_exists $name

    # xbacklight
    # ----------
    #   Notes:
    #   Only Intel graphics drivers supported.
    #   Querying identifier for the main display: 'Screen 0'.
    #   If this doesn't work, do the following:
    #   Check output from 'xrandr --verbose' command and manually insert correct identifier value into 20-intel.conf.
    #

    local graphics=$(lspci | grep VGA | grep -oP 'Intel')

    if [ $graphics = "Intel" ]; then
        pkg xbacklight

        local identifier=$(xrandr --verbose | grep -oP -m 1 '(?<=Identifier: )\w+')

        sed -i "s/UNDEFINED/$identifier/g" $BASE_DIR/etc/$name/20-intel.conf

        $ROOT_INSTALL -d /etc/X11/xorg.conf.d/
        $ROOT_INSTALL --mode=644 $BASE_DIR/etc/$name/20-intel.conf /etc/X11/xorg.conf.d/

        echo_ok "xbacklight configured." ;
    fi

    echo_inf "Starting firefox to generate a 'default-esr' profile..."
    sudo -u $SUDO_USER firefox-esr & disown
    sleep 3

    ESR_DIR=$(cd /home/$SUDO_USER/.mozilla/firefox/ && find -type d -iname "*.default-esr" | cut -c 3-)
    if ! [ -d "/home/$SUDO_USER/.mozilla/firefox/$ESR_DIR" ]; then
        error 3 "No .mozilla/ directory generated"
    fi

    # /org/gtk/settings/
    sudo -u $SUDO_USER dconf write /org/gtk/settings/date-format "'regular'"
    sudo -u $SUDO_USER dconf write /org/gtk/settings/location-mode "'path-bar'"
    sudo -u $SUDO_USER dconf write /org/gtk/settings/show-hidden true
    sudo -u $SUDO_USER dconf write /org/gtk/settings/show-size-column true
    sudo -u $SUDO_USER dconf write /org/gtk/settings/sidebar-width 202
    sudo -u $SUDO_USER dconf write /org/gtk/settings/sort-directories-first true
    sudo -u $SUDO_USER dconf write /org/gtk/settings/type-format "'mime'"
    echo_ok "GTK configured." ;

    # /org/gnome/desktop/interface
    sudo -u $SUDO_USER dconf write /org/gnome/desktop/interface/font-name "'Clear Sans 11'"
    sudo -u $SUDO_USER dconf write /org/gnome/desktop/interface/gtk-theme "'at-deb-dark'"
    sudo -u $SUDO_USER dconf write /org/gnome/desktop/interface/icon-theme "'Boston-at-deb'"
    sudo -u $SUDO_USER dconf write /org/gnome/desktop/interface/monospace-font-name "'JetBrains Mono 11'"
    echo_ok "GNOME desktop configured." ;

    # /org/nemo/
    sudo -u $SUDO_USER dconf write /org/nemo/icon-view/default-zoom-level "'small'"
    sudo -u $SUDO_USER dconf write /org/nemo/icon-view/labels-beside-icons false
    sudo -u $SUDO_USER dconf write /org/nemo/list-view/default-column-order "['name', 'size', 'type', 'detailed_type', 'date_modified', 'date_created_with_time', 'date_accessed', 'date_created', 'group', 'where', 'mime_type', 'date_modified_with_time', 'octal_permissions', 'owner', 'permissions', 'selinux_context']"
    sudo -u $SUDO_USER dconf write /org/nemo/list-view/default-visible-columns "['name', 'size', 'detailed_type', 'date_modified', 'date_created_with_time', 'octal_permissions']"
    sudo -u $SUDO_USER dconf write /org/nemo/plugins/disabled-actions "['set-resolution.nemo_action', 'mount-archive.nemo_action', 'add-desklets.nemo_action', 'change-background.nemo_action', 'set-as-background.nemo_action']"
    sudo -u $SUDO_USER dconf write /org/nemo/plugins/disabled-extensions "['NemoFileRoller']"
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/default-sort-order "'type'"
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/detect-content false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/executable-text-activation "'display'"
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-advanced-permissions true
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-bookmarks-in-to-menus false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-compact-view-icon-toolbar false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-edit-icon-toolbar false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-hidden-files true
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-location-entry true
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-next-icon-toolbar false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-places-in-to-menus false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/show-search-icon-toolbar false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/sort-favorites-first false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/window-state/sidebar-bookmark-breakpoint 0
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/window-state/sidebar-width 173
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/window-state/side-pane-view "'tree'"
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/window-state/start-with-sidebar false
    sudo -u $SUDO_USER dconf write /org/nemo/preferences/window-state/start-with-toolbar true
    echo_ok "nemo configured." ;

    # /org/xfce/mousepad/
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/auto-indent true
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/color-scheme "'at-deb-dark'"
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/font-name "'JetBrains Mono 11'"
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/highlight-current-line false
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/match-braces true
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/show-line-endings false
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/show-line-numbers true
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/show-whitespace false
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/view/word-wrap true
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/window/menubar-visible false
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/window/opening-mode "'window'"
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/window/path-in-title false
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/window/remember-size false
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/window/remember-state false
    sudo -u $SUDO_USER dconf write /org/xfce/mousepad/preferences/window/statusbar-visible true
    echo_ok "Mousepad configured." ;

    # Set default apps
    $USR_INSTALL -d /home/$SUDO_USER/.local/share/applications
    echo "[Default Applications]
text/css=code.desktop
text/html=code.desktop
text/x-javascript=code.desktop
text/xml=code.desktop
text/plain=org.xfce.mousepad.desktop
text/markdown=org.xfce.mousepad.desktop
application/x-shellscript=vim.desktop
application/javascript=code.desktop
application/pdf=org.gnome.Evince.desktop
image/png=qimgv.desktop
image/jpg=qimgv.desktop
image/jpeg=qimgv.desktop
image/gif=qimgv.desktop
image/bmp=qimgv.desktop
image/webp=qimgv.desktop" | sudo -u $SUDO_USER tee -a /home/$SUDO_USER/.local/share/applications/mimeapps.list

    $BASE_DIR/etc/$name/customise-firefox-esr.sh ; echo

    apt_routine

    set_snapper_apt_rule 1
}
