#!/bin/bash

# Bash
code --install-extension rogalmic.bash-debug
code --install-extension timonwong.shellcheck

# C / Embedded
code --install-extension marus25.cortex-debug
code --install-extension mcu-debug.debug-tracker-vscode
code --install-extension mcu-debug.memory-view
code --install-extension mcu-debug.peripheral-viewer
code --install-extension mcu-debug.rtos-views
code --install-extension ms-vscode.cmake-tools
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.cpptools-extension-pack
code --install-extension ms-vscode.makefile-tools
code --install-extension ms-vscode.vscode-serial-monitor
code --install-extension trond-snekvik.gnu-mapfiles
code --install-extension twxs.cmake

# Rust
code --install-extension rust-lang.rust-analyzer
code --install-extension tamasfe.even-better-toml

# Python
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance

# Web
code --install-extension alexcvzz.vscode-sqlite
code --install-extension dbaeumer.vscode-eslint
code --install-extension dlasagno.rasi
code --install-extension ecmel.vscode-html-css
code --install-extension karunamurti.tera
code --install-extension lehwark.htmx-literals
code --install-extension pranaygp.vscode-css-peek
code --install-extension rangav.vscode-thunder-client
code --install-extension xabikos.javascriptsnippets
code --install-extension Zignd.html-css-class-completion

# Misc
code --install-extension mhutchie.git-graph
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension tomoki1206.pdf
code --install-extension vscodevim.vim
code --install-extension yzhang.markdown-all-in-one
