#!/bin/bash

BAT_PATH="/sys/class/power_supply/BAT0"
STATUS_FILE="$BAT_PATH/status"
CAPACITY_FILE="$BAT_PATH/capacity"

# Notification function
print_critical() {
    local low="$1"
    notify-send -u critical "Connect charger" "Battery is at ${low}%."
}

is_notified=0

# Poll every 120 seconds
while true; do
    status=$(<"$STATUS_FILE")

    if [[ "$status" != "Discharging" ]]; then
        is_notified=0
    else
        percent=$(<"$CAPACITY_FILE")

        if (( is_notified == 1 && percent <= 8 )); then
            print_critical "$percent"
        elif (( is_notified == 1 && percent <= 23 )); then
            print_critical "$percent"
            sleep 180
        elif (( is_notified == 0 && percent <= 29 )); then
            is_notified=1
            print_critical "$percent"
            sleep 480
        fi
    fi

    sleep 120
done
