#! /bin/sh

# sxhkd
if ! pgrep -x sxhkd > /dev/null; then
	sxhkd &
fi

# Monitor settings
xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal

# Monitor settings: override if HDMI1 connected
bash hdmi_init &

# bspwm Settings
bspc monitor eDP1 -d 0 1 2 3 4 5 6
bspc monitor HDMI1 -d 7 8 9 10 11 12 13

bspc config border_width				0
bspc config border_radius				6
bspc config window_gap					4
bspc config top_padding					29
bspc config right_padding				0
bspc config bottom_padding				0
bspc config left_padding				0
bspc config split_ratio					0.53
bspc config top_monocle_padding			-29
bspc config left_monocle_padding		0
bspc config bottom_monocle_padding		0
bspc config right_monocle_padding		0
bspc config borderless_monocle			true
bspc config single_monocle				false
bspc config gapless_monocle				true
bspc config focus_follows_pointer		true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config pointer_action1				move
bspc config pointer_action2				resize_corner
bspc config pointer_action3				resize_side

#### coloring ####
# background = 	#222223
# foreground = 	#f9f9f9
# gray	= 	#555555
# red 	= 	#ff3e7a
# green = 	#55ff55
# yellow = 	#ffff55
# blue = 	#0048ff
# lilac = 	#ff55e9
# cyan = 	#55ffff
# white	= 	#f8f8f8
# alert	= 	#ff0054
# selection = 	#3f3f41
# blue_darker =	#0006ff

bspc config normal_border_color		"#2f2f30"
bspc config active_border_color		"#2f2f30"
bspc config focused_border_color	"#55ffff"
bspc config presel_feedback_color	"#2f2f30"

bspc rule -a Dialog state=floating center=on
bspc rule -a Code desktop='^3' follow=off
bspc rule -a discord monitor=eDP1 desktop='^7' follow=on

# Policykit
if ! pgrep -f /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 > /dev/null; then
	/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
fi

# Touchpad settings
bash /usr/local/libexec/touchpad_init &

# Custom braceleft, braceright
xmodmap /home/$USER/.Xmodmap

# Battery polling
if ! pgrep -x battery_poll > /dev/null; then
	bash /usr/local/libexec/battery_poll &
fi

# Lockscreen
if ! pgrep -x xss-lock > /dev/null; then
	xss-lock -- /usr/local/bin/lockscreen &
fi

# Compositor
if ! pgrep -x picom > /dev/null; then
	picom --daemon &
fi

# Restart daemons
# ---------------
# Needed for /usr/local/bin/themes functionality

# Notification daemon
if ! pgrep -x dunst > /dev/null; then
	dunst &
elif pgrep -x dunst > /dev/null; then
	kill -15 "$(pidof dunst)" && dunst &
fi

# xsettings daemon
if ! pgrep -x xsettingsd > /dev/null; then
	xsettingsd &
elif pgrep -x xsettingsd > /dev/null; then
	kill -15 "$(pidof xsettingsd)" && xsettingsd &
fi

# Wallpaper
while read line; do
	selected=$(echo $line)
done < /var/local/wallpapers/current-wallpaper

feh --bg-fill /usr/local/share/themes/at-deb-theme/wallpapers/$selected/desktop/1920x1080.png &

# Set Polybar environment variables
POLYBAR_WLP="$(cat /proc/net/wireless | grep -oP 'wlp[^:]+')"
export POLYBAR_WLP

# Polybar
bash /usr/local/libexec/polybar_init &
bash /usr/local/libexec/polybar_hdmi_init &

# xfce4-clipman
if ! pgrep -x xfce4-clipman > /dev/null; then
	xfce4-clipman &
fi
