#!/bin/bash

hdmi_status=$(xrandr --current | xrandr --current | grep -oP -m 1 '(?<=HDMI1 )\w+')
if [[ $hdmi_status == "connected" ]]; then
	xrandr --output eDP1 --primary --mode 1920x1080 --rotate normal --output HDMI1 --mode 1920x1080 --rotate normal --above eDP1
fi
