#!/bin/bash

DISABLED=0

while sleep 2; do
  if pactl list | grep -q RUNNING; then
    if [[ "$DISABLED" -eq 0 ]]; then
      killall xss-lock
    fi
    xset -dpms
    xset s off
    DISABLED=1
  else
    if [[ "$DISABLED" -eq 1 ]]; then
      if ! pgrep -x xss-lock > /dev/null; then
        xss-lock --transfer-sleep-lock -- /usr/local/bin/lockscreen &
      fi
      xset +dpms
      xset s on
      DISABLED=0
    fi
  fi
done