#!/bin/bash

## CONFIGURATION ##############################################################

while read line; do
	selected=$(echo $line)
done < /var/local/wallpapers/current-wallpaper

i3lock_options="-i /usr/local/share/themes/at-deb-theme/wallpapers/$selected/lockscreen/1920x1080.png -e -u -t"

# Run before starting the locker
pre_lock() {
    if pgrep -x picom > /dev/null; then
        pkill -x picom
    fi
    return
}

# Run after the locker exits
post_lock() {
    if ! pgrep -x picom > /dev/null; then
        picom --deamon &
    fi
}

###############################################################################

pre_lock

# We set a trap to kill the locker if we get killed, then start the locker and
# wait for it to exit. The waiting is not that straightforward when the locker
# forks, so we use this polling only if we have a sleep lock to deal with.
if [[ -e /dev/fd/${XSS_SLEEP_LOCK_FD:--1} ]]; then
    kill_i3lock() {
        pkill -xu $EUID "$@" i3lock
    }

    trap kill_i3lock TERM INT

    # we have to make sure the locker does not inherit a copy of the lock fd
    i3lock "$i3lock_options" {XSS_SLEEP_LOCK_FD}<&-

    # now close our fd (only remaining copy) to indicate we're ready to sleep
    exec {XSS_SLEEP_LOCK_FD}<&-

    while kill_i3lock -0; do
        sleep 0.5
    done
else
    trap 'kill %%' TERM INT
    i3lock -n "$i3lock_options" &
    wait
fi

post_lock