#!/bin/bash

DISABLED=0

while :
do
    DISABLE_LOCKSCREEN="$(pactl list | grep -c RUNNING)"

    if [[ $DISABLE_LOCKSCREEN -ne "0" && $DISABLED -eq 0 ]]; then
        if pgrep -x xss-lock > /dev/null; then
           kill -15 "$(pidof xss-lock)";
           xset -dpms;
           xset s off;
        fi
        DISABLED=1
    else
        if ! pgrep -x xss-lock > /dev/null; then
            xss-lock -- /usr/local/bin/lockscreen &
            xset +dpms;
            xset s on;
        fi
	DISABLED=0
    fi

     echo $DISABLED;
    echo $DISABLE_LOCKSCREEN;
    echo ;


    if [ $DISABLED -eq 1 ]; then
	    sleep 30;
    fi

    sleep 2;
   done
