#!/bin/bash

CURRENT_WORKSPACE="$(bspc query -D -d focused --names)"
CURRENT_WINDOW="$(bspc query -N -n focused.window)"

set_light(){
	sed -i '/Net\/ThemeName/c\Net\/ThemeName "at-deb-light"' /home/$USER/.xsettingsd
	dconf write /org/xfce/mousepad/preferences/view/color-scheme "'at-deb-light'"
	sed -i "s/#f8f8f8/#070707/" /home/$USER/.config/dunst/dunstrc
	sed -i "s/#222223/#dddddc/" /home/$USER/.config/dunst/dunstrc
	sed -i "s/#333335/#ccccc5/" /home/$USER/.config/dunst/dunstrc
	sed -i "/BackgroundDarkness=/c\BackgroundDarkness=0.200000" /home/$USER/.config/xfce4/terminal/terminalrc
	bspc wm -r
	sleep 1
	bspc desktop -f $CURRENT_WORKSPACE -a
	xdo activate $CURRENT_WINDOW
	notify-send "themes" "Light theme was set."
}

set_dark(){
	sed -i '/Net\/ThemeName/c\Net\/ThemeName "at-deb-dark"' /home/$USER/.xsettingsd
	dconf write /org/xfce/mousepad/preferences/view/color-scheme "'at-deb-dark'"
	sed -i "s/#070707/#f8f8f8/" /home/$USER/.config/dunst/dunstrc
	sed -i "s/#dddddc/#222223/" /home/$USER/.config/dunst/dunstrc
	sed -i "s/#ccccc5/#333335/" /home/$USER/.config/dunst/dunstrc
	sed -i "/BackgroundDarkness=/c\BackgroundDarkness=0.600000" /home/$USER/.config/xfce4/terminal/terminalrc
	bspc wm -r
	sleep 1
	bspc desktop -f $CURRENT_WORKSPACE -a
	xdo activate $CURRENT_WINDOW
	notify-send "themes" "Dark theme was set."
}

if [ "$(cat /home/$USER/.xsettingsd | grep -oP '(?<=Net/ThemeName "at-deb-)\w+')" = "dark" ]; then
	set_light
elif [ "$(cat /home/$USER/.xsettingsd | grep -oP '(?<=Net/ThemeName "at-deb-)\w+')" = "light" ]; then
	set_dark
fi

exit 0