#! /bin/sh

# Touchpad Settings
# Get Touchpad id
TOUCHPAD=$(xinput list | grep Touchpad | grep -oP '(?<=id=)[0-9]+')

if [ ${#touchpad} -eq 0 ]; then
    TOUCHPAD=$(xinput list | grep Synaptics | grep -oP '(?<=id=)[0-9]+')
fi

# Get Settings id
# Tapping Enabled
TAPPING=$(xinput list-props $TOUCHPAD | grep -oP '(?<=Tapping Enabled \()[0-9]+')
# Natural Scrolling
SCROLLING=$(xinput list-props $TOUCHPAD | grep -oP '(?<=Natural Scrolling Enabled \()[0-9]+')
ACC=$(xinput list-props $TOUCHPAD | grep -oP '(?<=Accel Speed \()[0-9]+')

#Set Settings
xinput set-prop $TOUCHPAD --type=int $TAPPING 1
xinput set-prop $TOUCHPAD --type=int $SCROLLING 1
xinput set-prop $TOUCHPAD --type=float $ACC 0.1

exit 0