#!/bin/sh

# Get previously selected wallpaper
while read line; do
	prev=$(echo $line)
done < /var/local/wallpapers/current-wallpaper

# Rofi config file
rofi_theme="/usr/local/lib/wallpapers/wallpapers.rasi"

# Get new wallpaper selection
next=$(printf '%s\n' "default" "darker" "lines" "colorful"  | rofi -dmenu -theme $rofi_theme -p "Set wallpaper:")

# Set new selected value
echo $next > /var/local/wallpapers/current-wallpaper

# If root, change LightDM background
[ $UID -eq 0 ] && sed -i "s/$prev\//$next\//" /etc/lightdm/lightdm-gtk-greeter.conf

# Change background image
feh --bg-fill /usr/local/share/themes/at-deb-theme/wallpapers/$next/desktop/1920x1080.png